#!/usr/bin/env bash
# One-time setup for the local lakeFS + MinIO stack (native binaries, no Docker).
# Downloads the binaries, generates credentials, and writes the lakeFS config.
# Idempotent: re-running skips finished steps and never regenerates credentials.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BIN="$HERE/bin"
DATA="$HERE/data"
LOGS="$HERE/logs"
LAKEFS_VERSION="1.83.0"

mkdir -p "$BIN" "$DATA/minio" "$DATA/lakefs" "$LOGS"

# ── Binaries ──────────────────────────────────────────────────────────────────
if [ ! -x "$BIN/minio" ]; then
    echo "Downloading MinIO..."
    curl -fsSL -o "$BIN/minio" https://dl.min.io/server/minio/release/linux-amd64/minio
    chmod +x "$BIN/minio"
fi

if [ ! -x "$BIN/mc" ]; then
    echo "Downloading MinIO client (mc)..."
    curl -fsSL -o "$BIN/mc" https://dl.min.io/client/mc/release/linux-amd64/mc
    chmod +x "$BIN/mc"
fi

if [ ! -x "$BIN/lakefs" ]; then
    echo "Downloading lakeFS $LAKEFS_VERSION..."
    curl -fsSL -o /tmp/lakefs.tar.gz \
        "https://github.com/treeverse/lakeFS/releases/download/v${LAKEFS_VERSION}/lakeFS_${LAKEFS_VERSION}_Linux_x86_64.tar.gz"
    tar -xzf /tmp/lakefs.tar.gz -C "$BIN" lakefs lakectl
    rm /tmp/lakefs.tar.gz
fi

# ── Credentials (generated once, never overwritten) ───────────────────────────
if [ ! -f "$HERE/local.env" ]; then
    echo "Generating credentials..."
    python3 - "$HERE/local.env" <<'PY'
import secrets, sys
out = sys.argv[1]
lines = [
    "MINIO_ROOT_USER=lips-minio",
    f"MINIO_ROOT_PASSWORD={secrets.token_urlsafe(18)}",
    f"LAKEFS_ACCESS_KEY_ID=AKIALIPS{secrets.token_hex(6).upper()}",
    f"LAKEFS_SECRET_ACCESS_KEY={secrets.token_urlsafe(30)}",
    f"LAKEFS_ENCRYPT_SECRET={secrets.token_urlsafe(30)}",
]
open(out, "w").write("\n".join(lines) + "\n")
PY
    chmod 600 "$HERE/local.env"
fi
# shellcheck disable=SC1091
source "$HERE/local.env"

# ── lakeFS config (regenerated from local.env so the two never drift) ─────────
cat > "$HERE/lakefs.yaml" <<EOF
# Generated by setup.sh from local.env — do not edit by hand, do not commit.
listen_address: "127.0.0.1:8000"
logging:
  level: INFO
database:
  type: local
  local:
    path: "$DATA/lakefs/metadata"
auth:
  encrypt:
    secret_key: "$LAKEFS_ENCRYPT_SECRET"
blockstore:
  type: s3
  s3:
    endpoint: http://127.0.0.1:9000
    force_path_style: true
    discover_bucket_region: false
    credentials:
      access_key_id: "$MINIO_ROOT_USER"
      secret_access_key: "$MINIO_ROOT_PASSWORD"
EOF
chmod 600 "$HERE/lakefs.yaml"

echo "Setup complete. Run ./start.sh to launch MinIO + lakeFS."
echo "App credentials for .env:"
echo "  LAKEFS_ENDPOINT=http://127.0.0.1:8000"
echo "  LAKEFS_ACCESS_KEY_ID=$LAKEFS_ACCESS_KEY_ID"
echo "  LAKEFS_SECRET_ACCESS_KEY=(see $HERE/local.env)"
